exclude: 
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "TODO.md"
gems:
  - jekyll-optional-front-matter
  - jekyll-redirect-from
host: 0.0.0.0
plugins:
  - jekyll-cs50-theme
port: 8080
