exclude: 
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "TODO.md"
gems:
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - 2.rb
host: 0.0.0.0
port: 8080
plugins_dir: [2.rb]